import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ThemedText } from '@/components/themed-text'; import { ThemedView } from '@/components/themed-view'; import { Spacing } from '@/constants/theme'; import { useAuth } from '@/lib/auth'; import { startOutboundCall } from '@/lib/api';
import { IS_DEMO_MODE } from '@/lib/demo';
function valid(raw: string) { return /^\d{10,15}$/.test(raw.trim().replace(/^\+/, '').replace(/[\s().-]/g, '')); }
export default function CallCustomerScreen() { const router=useRouter(); const {user}=useAuth(); const [rep,setRep]=useState(user?.phone||''); const [customer,setCustomer]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [ringing,setRinging]=useState(false);
async function call(){ setError(null); if(!valid(rep)||!valid(customer)) return setError('Enter valid rep and customer phone numbers.'); setBusy(true); try{const r=await startOutboundCall(rep.trim(),customer.trim()); setRinging(true); if(r.meetingId) router.replace({pathname:'/meetings/[id]',params:{id:r.meetingId}});}catch(e){setError(e instanceof Error?e.message:'Failed to place call.');}finally{setBusy(false);} }
return <ThemedView style={styles.fill}><SafeAreaView style={styles.fill}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="arrow-back" size={23} color="#DBEAFE"/></Pressable><ThemedText type="title" style={styles.headerTitle}>Call a Customer</ThemedText></View><View style={styles.content}><View style={styles.notice}><Ionicons name="radio-button-on" size={20} color="#B45309"/><ThemedText type="small" style={styles.noticeText}>{IS_DEMO_MODE ? 'ARIA TEST is offline. Customer calls and production access are disabled.' : 'This call will be recorded. ARIA calls you first, plays the recording disclosure, then connects the customer.'}</ThemedText></View>{ringing?<View style={styles.card}><ThemedText style={styles.big}>📱</ThemedText><ThemedText type="subtitle">ARIA is calling your phone</ThemedText><ThemedText type="small" themeColor="textSecondary" style={styles.center}>Answer to be connected to the customer.</ThemedText></View>:<View style={styles.card}>{error&&<View style={styles.error}><ThemedText type="small" style={styles.errorText}>{error}</ThemedText></View>}<ThemedText type="smallBold" style={styles.label}>Your Phone Number</ThemedText><TextInput value={rep} onChangeText={setRep} keyboardType="phone-pad" placeholder="(616) 555-1234" style={styles.input}/><ThemedText type="small" themeColor="textSecondary">ARIA calls this number first.</ThemedText><ThemedText type="smallBold" style={styles.label}>Customer's Phone Number</ThemedText><TextInput value={customer} onChangeText={setCustomer} keyboardType="phone-pad" placeholder="(616) 555-6789" style={styles.input}/><Pressable onPress={call} disabled={busy||IS_DEMO_MODE} style={({pressed})=>[styles.button,pressed&&styles.pressed,(busy||IS_DEMO_MODE)&&styles.disabled]}>{busy?<ActivityIndicator color="#fff"/>:<><Ionicons name="call" size={20} color="#fff"/><ThemedText style={styles.buttonText}>{IS_DEMO_MODE?'Calling Disabled in ARIA TEST':'Start Phone Meeting'}</ThemedText></>}</Pressable></View>}</View></SafeAreaView></ThemedView>}
const styles=StyleSheet.create({fill:{flex:1,backgroundColor:'#F3F4F6'},header:{backgroundColor:'#1D4ED8',padding:Spacing.three,flexDirection:'row',alignItems:'center',gap:Spacing.three},back:{width:40,height:40,borderRadius:20,backgroundColor:'#2563EB',alignItems:'center',justifyContent:'center'},headerTitle:{color:'#fff',fontSize:24},content:{padding:Spacing.three,gap:Spacing.three},notice:{backgroundColor:'#FFFBEB',borderWidth:1,borderColor:'#FDE68A',borderRadius:14,padding:Spacing.three,flexDirection:'row',gap:Spacing.two},noticeText:{flex:1,color:'#78350F',lineHeight:20},card:{backgroundColor:'#fff',borderRadius:18,padding:Spacing.four,borderWidth:1,borderColor:'#E5E7EB',gap:Spacing.two},label:{color:'#374151',marginTop:Spacing.two},input:{minHeight:52,borderWidth:1,borderColor:'#CBD5E1',borderRadius:12,paddingHorizontal:Spacing.three,fontSize:16},button:{minHeight:54,borderRadius:12,backgroundColor:'#1D4ED8',marginTop:Spacing.four,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:Spacing.two},buttonText:{color:'#fff',fontWeight:'900',fontSize:16},error:{backgroundColor:'#FEF2F2',borderRadius:10,padding:Spacing.three},errorText:{color:'#B91C1C'},pressed:{opacity:.75},disabled:{opacity:.5},big:{fontSize:44,textAlign:'center'},center:{textAlign:'center'}})
