import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { Spacing } from '@/constants/theme';
import { getObjection, listObjections, Objection, ObjectionWithRebuttals } from '@/lib/api';

export default function ObjectionsScreen() {
  const router = useRouter();
  const [items, setItems] = useState<Objection[]>([]); const [selected, setSelected] = useState<ObjectionWithRebuttals | null>(null);
  const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); try { setItems(await listObjections()); setError(null); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load objections.'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return q ? items.filter((o) => o.text.toLowerCase().includes(q) || (o.category || '').toLowerCase().includes(q)) : items; }, [items, query]);
  async function open(item: Objection) { setLoading(true); try { setSelected(await getObjection(item.id)); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load rebuttals.'); } finally { setLoading(false); } }
  return <ThemedView style={styles.fill}><SafeAreaView style={styles.fill}><View style={styles.header}><Pressable onPress={() => selected ? setSelected(null) : router.back()} style={styles.back}><Ionicons name="arrow-back" size={23} color="#DBEAFE" /></Pressable><View><ThemedText type="title" style={styles.headerTitle}>{selected ? 'Rebuttals' : 'Objections'}</ThemedText><ThemedText type="small" style={styles.headerSub}>{selected ? 'What works in the field' : 'Common customer concerns and responses'}</ThemedText></View></View>
    {loading ? <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View> : selected ? <FlatList contentContainerStyle={styles.content} data={selected.rebuttals} keyExtractor={(r) => r.id} ListHeaderComponent={<View style={styles.selectedCard}><ThemedText type="small" style={styles.category}>{selected.category || 'OBJECTION'}</ThemedText><ThemedText type="subtitle">{selected.text}</ThemedText></View>} ListEmptyComponent={<View style={styles.empty}><ThemedText type="small" themeColor="textSecondary">No rebuttals have been added yet.</ThemedText></View>} renderItem={({ item, index }) => <View style={styles.rebuttal}><View style={styles.number}><ThemedText style={styles.numberText}>{index + 1}</ThemedText></View><ThemedText type="small" style={styles.rebuttalText}>{item.text}</ThemedText></View>} /> : <FlatList contentContainerStyle={styles.content} data={filtered} keyExtractor={(o) => o.id} ListHeaderComponent={<><TextInput value={query} onChangeText={setQuery} placeholder="Search objections…" style={styles.search} />{error && <View style={styles.error}><ThemedText type="small" style={styles.errorText}>{error}</ThemedText><Pressable onPress={load}><ThemedText type="link">Retry</ThemedText></Pressable></View>}</>} ListEmptyComponent={<View style={styles.empty}><ThemedText style={styles.emptyIcon}>💬</ThemedText><ThemedText type="small" themeColor="textSecondary">No objections match your search.</ThemedText></View>} renderItem={({ item }) => <Pressable onPress={() => open(item)} style={({ pressed }) => [styles.item, pressed && styles.pressed]}><View style={styles.itemCopy}><ThemedText type="smallBold">{item.text}</ThemedText>{item.category && <ThemedText type="small" style={styles.category}>{item.category}</ThemedText>}</View><View style={styles.count}><ThemedText type="small" style={styles.countText}>{item.rebuttal_count || 0}</ThemedText></View><Ionicons name="chevron-forward" size={20} color="#94A3B8" /></Pressable>} />}
  </SafeAreaView></ThemedView>;
}
const styles = StyleSheet.create({ fill: { flex: 1, backgroundColor: '#F3F4F6' }, header: { backgroundColor: '#1D4ED8', padding: Spacing.three, flexDirection: 'row', alignItems: 'center', gap: Spacing.three }, back: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#2563EB', alignItems: 'center', justifyContent: 'center' }, headerTitle: { color: '#fff', fontSize: 24 }, headerSub: { color: '#DBEAFE', marginTop: 2 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, content: { padding: Spacing.three, gap: Spacing.two, paddingBottom: Spacing.six }, search: { minHeight: 50, backgroundColor: '#fff', borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 12, paddingHorizontal: Spacing.three, fontSize: 15, marginBottom: Spacing.two }, item: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#E5E7EB', padding: Spacing.three, flexDirection: 'row', alignItems: 'center', gap: Spacing.two }, itemCopy: { flex: 1, gap: 4 }, category: { color: '#2563EB', fontWeight: '900', textTransform: 'uppercase', letterSpacing: 0.6 }, count: { minWidth: 30, height: 30, borderRadius: 15, backgroundColor: '#F1F5F9', alignItems: 'center', justifyContent: 'center' }, countText: { color: '#475569', fontWeight: '800' }, selectedCard: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#DBEAFE', padding: Spacing.four, gap: Spacing.two, marginBottom: Spacing.two }, rebuttal: { backgroundColor: '#fff', borderRadius: 16, padding: Spacing.three, borderWidth: 1, borderColor: '#E5E7EB', flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.three }, number: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#DBEAFE', alignItems: 'center', justifyContent: 'center' }, numberText: { color: '#1D4ED8', fontWeight: '900' }, rebuttalText: { flex: 1, lineHeight: 20 }, empty: { padding: Spacing.four, alignItems: 'center', gap: Spacing.two }, emptyIcon: { fontSize: 32 }, error: { backgroundColor: '#FEF2F2', borderRadius: 12, padding: Spacing.three, alignItems: 'center', gap: Spacing.two }, errorText: { color: '#B91C1C', textAlign: 'center' }, pressed: { opacity: 0.72 } });
