#!/usr/bin/env bash
# check-deploy-drift.sh
#
# Enforces the rule we broke twice on 2026-08-02/03: "Railway reporting
# SUCCESS does not mean the code actually running in production matches
# what's on `main`." Confirmed root cause both times: Railway can report a
# deploy as SUCCESS while having silently built/served a stale commit.
#
# This script is the "cron the rule" fix — instead of trusting a status field
# once and moving on, it periodically re-verifies, on its own, that:
#   1. The live Railway deployment's commitHash actually matches the tip of
#      origin/main (or logs a real, actionable drift warning if not).
#   2. The backend is actually reachable and healthy (not just "deployed").
#
# Exit code 0 = no drift, healthy. Exit code 1 = drift or health check failed
# (intended to be picked up by cron's default mail-on-error behavior, or by
# a wrapper that alerts a human — see NEXT STEPS at bottom of this file).

set -euo pipefail

REPO_DIR="/root/.openclaw/workspace/projects/siro-sales-helper/app"
SECRETS_FILE="/root/.openclaw/workspace/projects/siro-sales-helper/.env.secrets"
LOG_FILE="/root/.openclaw/workspace/memory/deploy-drift-log.md"

SERVICE_ID="da41e2cd-839f-4065-9caf-855ad73cef9e"       # aria-backend
ENVIRONMENT_ID="db05b291-780d-4d95-8cf1-8e8fd43ffc65"    # production
HEALTH_URL="https://aria-backend-production-0e99.up.railway.app/health"
GRAPHQL_URL="https://backboard.railway.app/graphql/v2"

timestamp() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }

log() {
  # Append a timestamped line to the drift log (create with a header if new).
  if [ ! -f "$LOG_FILE" ]; then
    echo "# Aria Deploy Drift Log" > "$LOG_FILE"
    echo "" >> "$LOG_FILE"
    echo "Auto-generated by scripts/check-deploy-drift.sh. Enforces: never trust" >> "$LOG_FILE"
    echo "Railway's deploy status alone — verify the live commit hash and health" >> "$LOG_FILE"
    echo "on a schedule, not just once at deploy time." >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"
  fi
  echo "- $(timestamp) — $1" >> "$LOG_FILE"
}

RAILWAY_TOKEN="$(grep -m1 '^RAILWAY_TOKEN=' "$SECRETS_FILE" | cut -d= -f2-)"
if [ -z "$RAILWAY_TOKEN" ]; then
  log "❌ ERROR: could not read RAILWAY_TOKEN from $SECRETS_FILE"
  exit 1
fi

# ── Step 1: what commit does `main` actually point to right now? ───────────
EXPECTED_SHA="$(git -C "$REPO_DIR" ls-remote origin main | awk '{print $1}')"
if [ -z "$EXPECTED_SHA" ]; then
  log "❌ ERROR: could not resolve origin/main HEAD via git ls-remote"
  exit 1
fi

# ── Step 2: what commit does Railway say is LIVE right now? ────────────────
DEPLOY_RESPONSE="$(curl -s -X POST "$GRAPHQL_URL" \
  -H "Authorization: Bearer $RAILWAY_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{\"query\":\"query { deployments(input: {serviceId: \\\"$SERVICE_ID\\\", environmentId: \\\"$ENVIRONMENT_ID\\\"}, first: 1) { edges { node { status meta } } } }\"}")"

DEPLOYED_SHA="$(echo "$DEPLOY_RESPONSE" | grep -o '"commitHash":"[a-f0-9]*"' | head -1 | cut -d'"' -f4)"
DEPLOY_STATUS="$(echo "$DEPLOY_RESPONSE" | grep -o '"status":"[A-Z]*"' | head -1 | cut -d'"' -f4)"

if [ -z "$DEPLOYED_SHA" ]; then
  log "❌ ERROR: could not extract commitHash from Railway API response — raw: ${DEPLOY_RESPONSE:0:300}"
  exit 1
fi

# ── Step 3: do they actually match? (This is the check that would have ─────
#     caught both 2026-08-02 and 2026-08-03 incidents before a human noticed.)
DRIFT=0
if [ "$DEPLOYED_SHA" != "$EXPECTED_SHA" ]; then
  DRIFT=1
  log "🚨 DRIFT DETECTED — Railway status is '$DEPLOY_STATUS' but deployed commit ($DEPLOYED_SHA) does NOT match origin/main tip ($EXPECTED_SHA). This is exactly the failure mode that caused the 2026-08-02/03 analytics-feature incident. Action needed: check Railway dashboard, consider forcing a redeploy pinned to $EXPECTED_SHA."
fi

# ── Step 4: is the backend actually healthy right now, independent of Step 3? ─
HEALTH_RESPONSE="$(curl -s -m 10 "$HEALTH_URL" || echo '{"status":"unreachable"}')"
if ! echo "$HEALTH_RESPONSE" | grep -q '"status":"ok"'; then
  DRIFT=1
  log "🚨 HEALTH CHECK FAILED — $HEALTH_URL did not return status:ok. Raw response: ${HEALTH_RESPONSE:0:300}"
fi

if [ "$DRIFT" -eq 0 ]; then
  log "✅ OK — deployed commit ($DEPLOYED_SHA) matches origin/main, status=$DEPLOY_STATUS, health=ok."
  exit 0
else
  exit 1
fi
