-- 2026-08-05-meeting-auto-titled-flag.sql
--
-- PROPOSED / SKETCH ONLY — NOT APPLIED TO PRODUCTION. Follow-up to the
-- 2026-08-05 auto-title feature (see server.js's generateAutoTitleForMeeting()
-- doc comment for full history — originally shipped mobile-only, then
-- generalized to fire for both mobile- and web-started meetings in this
-- same follow-up pass, per Gabe's explicit decision).
--
-- Purpose: distinguish "this title was AI-generated by
-- generateAutoTitleForMeeting()" from "a human manually set/edited this
-- title" — previously there was no way to tell the two apart once a title
-- landed in the existing `title` column, since both write paths share that
-- one column with no accompanying marker.
--
-- This intentionally does NOT introduce a new title-storage column
-- (no `auto_title` alongside `title`) — the existing `title` column
-- continues to be the single source of truth for "the meeting's title,
-- however it got there." This migration only adds a boolean SIDE-FLAG
-- next to it.
--
-- Behavior (implemented in server.js as of this pass):
--   - generateAutoTitleForMeeting()'s UPDATE now sets `auto_titled = true`
--     in the same statement that sets `title`, whenever it successfully
--     writes a generated title (see its `UPDATE meetings SET title = $1,
--     auto_titled = true WHERE ...` call).
--   - PATCH /api/meetings/:id sets `auto_titled = false` whenever the
--     request body includes an explicit `title` field (a human/manual
--     title edit through the one existing title-write path in this repo)
--     — that edit is no longer "purely AI-generated," so the flag is
--     cleared alongside the title update in the same statement.
--   - Defaults to `false` for every existing row (all current titles in
--     prod are NULL/manually-set-only anyway — see the original auto-
--     title pass's report — so `false` is the factually correct default
--     for 100% of existing data, not just a placeholder).
--
-- Repo convention note: same idempotent `ALTER TABLE ... ADD COLUMN IF NOT
-- EXISTS` style as every other migration in this directory (no migration
-- framework exists in this repo — plain SQL only, run manually via
-- `psql`/`node` per DEPLOY.md, applied by a human after review).

BEGIN;

ALTER TABLE meetings
  ADD COLUMN IF NOT EXISTS auto_titled BOOLEAN NOT NULL DEFAULT false;

COMMIT;

-- ─── Why this is safe to apply later without much risk ────────────────────
-- Single NOT NULL ADD COLUMN IF NOT EXISTS with a DEFAULT, on an existing
-- table already handled this way elsewhere in this codebase (see
-- server.js's `ALTER TABLE meetings ADD COLUMN IF NOT EXISTS speaker_labels
-- JSONB DEFAULT '{}'` in ensureSessionsTable(), and the owner_session_id /
-- origin_client / channel / call_sid columns added by the other 2026-08-04
-- and 2026-08-05 migrations in this same directory). Every existing row
-- gets `auto_titled = false`, which is correct for all of them (no row in
-- prod has ever been auto-titled by this feature before this column
-- exists, by definition). No existing row's `title` value is touched, no
-- other column/table is altered, no data is deleted.

-- ─── Verification query (run manually after applying, if applied) ─────────
-- SELECT column_name, data_type, column_default, is_nullable
--   FROM information_schema.columns
--   WHERE table_name = 'meetings' AND column_name = 'auto_titled';
